# This file describes the network interfaces available on your system
# For more information, see netplan(5).
# It excludes eth0 interface described separately
network:
  version: 2
  renderer: networkd
  ethernets:
    host0:
     dhcp4: no
     addresses: [10.3.0.2/24]
     gateway4: 10.3.0.1
     nameservers:
       addresses: [8.8.8.8,1.1.1.1]

